[build]
  # Añadimos 'mkdir -p dist &&' al principio para asegurar que la carpeta exista
  command = "mkdir -p dist && npx @tailwindcss/cli -i ./src/input.css -o ./dist/output.css"
  publish = "."

[build.environment]
  NODE_VERSION = "20"